// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdate(arg1) {
  return window['go']['main']['App']['ApplyUpdate'](arg1);
}

export function BackupExportPackage() {
  return window['go']['main']['App']['BackupExportPackage']();
}

export function BackupGetManifestTemplate() {
  return window['go']['main']['App']['BackupGetManifestTemplate']();
}

export function BackupGetScopeDefinition() {
  return window['go']['main']['App']['BackupGetScopeDefinition']();
}

export function BackupImportPackage(arg1) {
  return window['go']['main']['App']['BackupImportPackage'](arg1);
}

export function BackupInitializeSystem() {
  return window['go']['main']['App']['BackupInitializeSystem']();
}

export function BookmarkList() {
  return window['go']['main']['App']['BookmarkList']();
}

export function BookmarkReset() {
  return window['go']['main']['App']['BookmarkReset']();
}

export function BookmarkSave(arg1) {
  return window['go']['main']['App']['BookmarkSave'](arg1);
}

export function BrowserClearCookies(arg1) {
  return window['go']['main']['App']['BrowserClearCookies'](arg1);
}

export function BrowserCoreDelete(arg1) {
  return window['go']['main']['App']['BrowserCoreDelete'](arg1);
}

export function BrowserCoreDownload(arg1, arg2, arg3) {
  return window['go']['main']['App']['BrowserCoreDownload'](arg1, arg2, arg3);
}

export function BrowserCoreExtendedInfo() {
  return window['go']['main']['App']['BrowserCoreExtendedInfo']();
}

export function BrowserCoreList() {
  return window['go']['main']['App']['BrowserCoreList']();
}

export function BrowserCoreSave(arg1) {
  return window['go']['main']['App']['BrowserCoreSave'](arg1);
}

export function BrowserCoreScan() {
  return window['go']['main']['App']['BrowserCoreScan']();
}

export function BrowserCoreSetDefault(arg1) {
  return window['go']['main']['App']['BrowserCoreSetDefault'](arg1);
}

export function BrowserCoreValidate(arg1) {
  return window['go']['main']['App']['BrowserCoreValidate'](arg1);
}

export function BrowserExportCookies(arg1) {
  return window['go']['main']['App']['BrowserExportCookies'](arg1);
}

export function BrowserGetAllTags() {
  return window['go']['main']['App']['BrowserGetAllTags']();
}

export function BrowserGetCookies(arg1) {
  return window['go']['main']['App']['BrowserGetCookies'](arg1);
}

export function BrowserInstanceGetTabs(arg1) {
  return window['go']['main']['App']['BrowserInstanceGetTabs'](arg1);
}

export function BrowserInstanceOpenUrl(arg1, arg2) {
  return window['go']['main']['App']['BrowserInstanceOpenUrl'](arg1, arg2);
}

export function BrowserInstanceRestart(arg1) {
  return window['go']['main']['App']['BrowserInstanceRestart'](arg1);
}

export function BrowserInstanceStart(arg1) {
  return window['go']['main']['App']['BrowserInstanceStart'](arg1);
}

export function BrowserInstanceStartByCode(arg1) {
  return window['go']['main']['App']['BrowserInstanceStartByCode'](arg1);
}

export function BrowserInstanceStartWithParams(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['BrowserInstanceStartWithParams'](arg1, arg2, arg3, arg4);
}

export function BrowserInstanceStatus(arg1) {
  return window['go']['main']['App']['BrowserInstanceStatus'](arg1);
}

export function BrowserInstanceStop(arg1) {
  return window['go']['main']['App']['BrowserInstanceStop'](arg1);
}

export function BrowserProfileBatchCreate(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['BrowserProfileBatchCreate'](arg1, arg2, arg3, arg4);
}

export function BrowserProfileBatchRemoveTags(arg1, arg2) {
  return window['go']['main']['App']['BrowserProfileBatchRemoveTags'](arg1, arg2);
}

export function BrowserProfileBatchSetTags(arg1, arg2, arg3) {
  return window['go']['main']['App']['BrowserProfileBatchSetTags'](arg1, arg2, arg3);
}

export function BrowserProfileCopy(arg1, arg2) {
  return window['go']['main']['App']['BrowserProfileCopy'](arg1, arg2);
}

export function BrowserProfileCreate(arg1) {
  return window['go']['main']['App']['BrowserProfileCreate'](arg1);
}

export function BrowserProfileDelete(arg1) {
  return window['go']['main']['App']['BrowserProfileDelete'](arg1);
}

export function BrowserProfileDeleteWithCache(arg1, arg2) {
  return window['go']['main']['App']['BrowserProfileDeleteWithCache'](arg1, arg2);
}

export function BrowserProfileGetCode(arg1) {
  return window['go']['main']['App']['BrowserProfileGetCode'](arg1);
}

export function BrowserProfileImportExtension(arg1, arg2) {
  return window['go']['main']['App']['BrowserProfileImportExtension'](arg1, arg2);
}

export function BrowserProfileImportMoreLoginXLSX() {
  return window['go']['main']['App']['BrowserProfileImportMoreLoginXLSX']();
}

export function BrowserProfileImportRunningMoreLogin() {
  return window['go']['main']['App']['BrowserProfileImportRunningMoreLogin']();
}

export function BrowserProfileList() {
  return window['go']['main']['App']['BrowserProfileList']();
}

export function BrowserProfileListByTag(arg1) {
  return window['go']['main']['App']['BrowserProfileListByTag'](arg1);
}

export function BrowserProfileRandomizeFingerprint(arg1) {
  return window['go']['main']['App']['BrowserProfileRandomizeFingerprint'](arg1);
}

export function BrowserProfileRegenerateCode(arg1) {
  return window['go']['main']['App']['BrowserProfileRegenerateCode'](arg1);
}

export function BrowserProfileSetCode(arg1, arg2) {
  return window['go']['main']['App']['BrowserProfileSetCode'](arg1, arg2);
}

export function BrowserProfileSetKeywords(arg1, arg2) {
  return window['go']['main']['App']['BrowserProfileSetKeywords'](arg1, arg2);
}

export function BrowserProfileUpdate(arg1, arg2) {
  return window['go']['main']['App']['BrowserProfileUpdate'](arg1, arg2);
}

export function BrowserProxyBatchCheckIPHealth(arg1, arg2) {
  return window['go']['main']['App']['BrowserProxyBatchCheckIPHealth'](arg1, arg2);
}

export function BrowserProxyBatchTestSpeed(arg1, arg2) {
  return window['go']['main']['App']['BrowserProxyBatchTestSpeed'](arg1, arg2);
}

export function BrowserProxyCheckIPHealth(arg1) {
  return window['go']['main']['App']['BrowserProxyCheckIPHealth'](arg1);
}

export function BrowserProxyFetchClashByURL(arg1) {
  return window['go']['main']['App']['BrowserProxyFetchClashByURL'](arg1);
}

export function BrowserProxyList() {
  return window['go']['main']['App']['BrowserProxyList']();
}

export function BrowserProxyListByGroup(arg1) {
  return window['go']['main']['App']['BrowserProxyListByGroup'](arg1);
}

export function BrowserProxyListGroups() {
  return window['go']['main']['App']['BrowserProxyListGroups']();
}

export function BrowserProxyTestSpeed(arg1) {
  return window['go']['main']['App']['BrowserProxyTestSpeed'](arg1);
}

export function BrowserRenameTag(arg1, arg2) {
  return window['go']['main']['App']['BrowserRenameTag'](arg1, arg2);
}

export function BrowserSnapshotCreate(arg1, arg2) {
  return window['go']['main']['App']['BrowserSnapshotCreate'](arg1, arg2);
}

export function BrowserSnapshotDelete(arg1, arg2) {
  return window['go']['main']['App']['BrowserSnapshotDelete'](arg1, arg2);
}

export function BrowserSnapshotList(arg1) {
  return window['go']['main']['App']['BrowserSnapshotList'](arg1);
}

export function BrowserSnapshotRestore(arg1, arg2) {
  return window['go']['main']['App']['BrowserSnapshotRestore'](arg1, arg2);
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function ClearAppLogs() {
  return window['go']['main']['App']['ClearAppLogs']();
}

export function ClearIntentionalExitMarker() {
  return window['go']['main']['App']['ClearIntentionalExitMarker']();
}

export function CloseWindowSyncPanel() {
  return window['go']['main']['App']['CloseWindowSyncPanel']();
}

export function CreateGroup(arg1) {
  return window['go']['main']['App']['CreateGroup'](arg1);
}

export function DeleteGroup(arg1) {
  return window['go']['main']['App']['DeleteGroup'](arg1);
}

export function DownloadUpdate(arg1, arg2) {
  return window['go']['main']['App']['DownloadUpdate'](arg1, arg2);
}

export function FetchRemoteAuthorProfile(arg1, arg2) {
  return window['go']['main']['App']['FetchRemoteAuthorProfile'](arg1, arg2);
}

export function ForceQuit() {
  return window['go']['main']['App']['ForceQuit']();
}

export function GenerateCDKeys(arg1) {
  return window['go']['main']['App']['GenerateCDKeys'](arg1);
}

export function GetAppConfig() {
  return window['go']['main']['App']['GetAppConfig']();
}

export function GetAppLogs() {
  return window['go']['main']['App']['GetAppLogs']();
}

export function GetBrowserSettings() {
  return window['go']['main']['App']['GetBrowserSettings']();
}

export function GetDashboardStats() {
  return window['go']['main']['App']['GetDashboardStats']();
}

export function GetInterceptor() {
  return window['go']['main']['App']['GetInterceptor']();
}

export function GetLaunchServerInfo() {
  return window['go']['main']['App']['GetLaunchServerInfo']();
}

export function GetLicenseStatus() {
  return window['go']['main']['App']['GetLicenseStatus']();
}

export function GetLogLevel() {
  return window['go']['main']['App']['GetLogLevel']();
}

export function GetMemoryStats() {
  return window['go']['main']['App']['GetMemoryStats']();
}

export function GetRunningInstances() {
  return window['go']['main']['App']['GetRunningInstances']();
}

export function GetSyncProfiles() {
  return window['go']['main']['App']['GetSyncProfiles']();
}

export function GetSyncStatus() {
  return window['go']['main']['App']['GetSyncStatus']();
}

export function InstallExtensionFromCRXURL(arg1, arg2) {
  return window['go']['main']['App']['InstallExtensionFromCRXURL'](arg1, arg2);
}

export function IsWindowSyncPanelMode() {
  return window['go']['main']['App']['IsWindowSyncPanelMode']();
}

export function ListGroups() {
  return window['go']['main']['App']['ListGroups']();
}

export function MoveInstancesToGroup(arg1, arg2) {
  return window['go']['main']['App']['MoveInstancesToGroup'](arg1, arg2);
}

export function OpenCorePath(arg1) {
  return window['go']['main']['App']['OpenCorePath'](arg1);
}

export function OpenUserDataDir(arg1) {
  return window['go']['main']['App']['OpenUserDataDir'](arg1);
}

export function OpenWindowSyncPanel() {
  return window['go']['main']['App']['OpenWindowSyncPanel']();
}

export function QuitAppOnly() {
  return window['go']['main']['App']['QuitAppOnly']();
}

export function RecordLifecycleEvent(arg1, arg2) {
  return window['go']['main']['App']['RecordLifecycleEvent'](arg1, arg2);
}

export function RedeemCDKey(arg1) {
  return window['go']['main']['App']['RedeemCDKey'](arg1);
}

export function RedeemGithubStar() {
  return window['go']['main']['App']['RedeemGithubStar']();
}

export function ReloadConfig() {
  return window['go']['main']['App']['ReloadConfig']();
}

export function SaveBrowserProxies(arg1) {
  return window['go']['main']['App']['SaveBrowserProxies'](arg1);
}

export function SaveBrowserSettings(arg1) {
  return window['go']['main']['App']['SaveBrowserSettings'](arg1);
}

export function SaveNativeMainWindowBounds(arg1) {
  return window['go']['main']['App']['SaveNativeMainWindowBounds'](arg1);
}

export function SetLogLevel(arg1) {
  return window['go']['main']['App']['SetLogLevel'](arg1);
}

export function StartInputSync(arg1, arg2) {
  return window['go']['main']['App']['StartInputSync'](arg1, arg2);
}

export function StartInstance(arg1) {
  return window['go']['main']['App']['StartInstance'](arg1);
}

export function StartInstanceWithParams(arg1, arg2) {
  return window['go']['main']['App']['StartInstanceWithParams'](arg1, arg2);
}

export function StopInputSync() {
  return window['go']['main']['App']['StopInputSync']();
}

export function SyncCloseAll(arg1) {
  return window['go']['main']['App']['SyncCloseAll'](arg1);
}

export function SyncTileWindows(arg1, arg2, arg3) {
  return window['go']['main']['App']['SyncTileWindows'](arg1, arg2, arg3);
}

export function TestProxyConnectivity(arg1, arg2) {
  return window['go']['main']['App']['TestProxyConnectivity'](arg1, arg2);
}

export function TestProxyRealConnectivity(arg1) {
  return window['go']['main']['App']['TestProxyRealConnectivity'](arg1);
}

export function TriggerGC() {
  return window['go']['main']['App']['TriggerGC']();
}

export function UpdateGroup(arg1, arg2) {
  return window['go']['main']['App']['UpdateGroup'](arg1, arg2);
}

export function UpdateSyncConfig(arg1, arg2) {
  return window['go']['main']['App']['UpdateSyncConfig'](arg1, arg2);
}

export function ValidateProxyConfig(arg1, arg2) {
  return window['go']['main']['App']['ValidateProxyConfig'](arg1, arg2);
}

export function WriteUpdateSuccessMarker() {
  return window['go']['main']['App']['WriteUpdateSuccessMarker']();
}
