# stage_assets.ps1
# Stage chromium kernels + proxy binaries + resource files to C:\Temp\BB_dist
# then generate build/windows/installer/bb_files.nsh (explicit NSIS File list).
#
# Why not File /r ?
#   1. NSIS File /r silently fails on paths containing dots
#      -> stage to C:\Temp\BB_dist (no dots in parent path) avoids that.
#   2. NSIS File /r does NOT match files without extension
#      (chrome has "First Run", "ABOUT" etc.)
#      -> emit explicit File commands enumerating every file.

$ErrorActionPreference = "Stop"
$RepoRoot = Split-Path -Parent $PSScriptRoot
Set-Location $RepoRoot

$StageRoot = "C:\Temp\BB_dist"
$NshFile   = "$RepoRoot\build\windows\installer\bb_files.nsh"

# Source = a known-working deployment
$SrcDeploy = $env:BOOST_KERNEL_SRC
if ([string]::IsNullOrWhiteSpace($SrcDeploy)) { throw "Set BOOST_KERNEL_SRC to the directory containing the Chromium kernels and runtime assets." }

Write-Host "==> Stage assets to $StageRoot" -ForegroundColor Cyan

if (Test-Path $StageRoot) {
    Write-Host "    cleaning old stage dir ..." -ForegroundColor Yellow
    Remove-Item -Recurse -Force $StageRoot
}
New-Item -ItemType Directory -Force -Path $StageRoot | Out-Null

# ---- 1. chrome kernels ----
$kernels = @(
    "cloak-146.0.7680.177",
    "google-148.0.7778.167"
)
New-Item -ItemType Directory -Force -Path "$StageRoot\chrome" | Out-Null

foreach ($k in $kernels) {
    $src = "$SrcDeploy\chrome\$k"
    $dst = "$StageRoot\chrome\$k"
    if (-not (Test-Path $src)) {
        throw "source not found: $src"
    }
    Write-Host "    chrome\$k ..." -ForegroundColor Gray
    robocopy $src $dst /E /NFL /NDL /NJH /NJS /NP | Out-Null
    if ($LASTEXITCODE -ge 8) { throw "robocopy failed (exit=$LASTEXITCODE) $src -> $dst" }
}

# ---- 2. bin proxy binaries ----
Write-Host "    bin\ ..." -ForegroundColor Gray
robocopy "$SrcDeploy\bin" "$StageRoot\bin" /E /NFL /NDL /NJH /NJS /NP | Out-Null
if ($LASTEXITCODE -ge 8) { throw "robocopy bin failed" }

# ---- 3. extensions/chromium-web-store ----
Write-Host "    extensions\chromium-web-store ..." -ForegroundColor Gray
New-Item -ItemType Directory -Force -Path "$StageRoot\extensions" | Out-Null
robocopy "$SrcDeploy\extensions\chromium-web-store" "$StageRoot\extensions\chromium-web-store" /E /NFL /NDL /NJH /NJS /NP | Out-Null
if ($LASTEXITCODE -ge 8) { throw "robocopy extensions failed" }

# ---- 4. top-level loose files ----
Write-Host "    top-level files ..." -ForegroundColor Gray
foreach ($f in @("app.ico", "app.png", ".boost-license.json")) {
    $src = "$SrcDeploy\$f"
    if (Test-Path $src) {
        Copy-Item $src "$StageRoot\$f" -Force
    } else {
        Write-Host "    WARN: $src missing, skip" -ForegroundColor Yellow
    }
}

$totalSize = (Get-ChildItem $StageRoot -Recurse -File | Measure-Object Length -Sum).Sum
$totalFiles = (Get-ChildItem $StageRoot -Recurse -File).Count
Write-Host ("==> Stage done: {0} files, {1:N0} MB" -f $totalFiles, ($totalSize/1MB)) -ForegroundColor Green

# ============================================================
# Generate bb_files.nsh - explicit File enumeration
# ============================================================
Write-Host "==> Generating $NshFile" -ForegroundColor Cyan

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add("; Auto-generated - do not edit by hand")
$lines.Add("; Generated by scripts\stage_assets.ps1")
$lines.Add("; Stage source: $StageRoot")
$lines.Add("")
$lines.Add("!macro bb.bundleAssets")

$allFiles = Get-ChildItem $StageRoot -Recurse -File
$grouped = $allFiles | Group-Object { $_.DirectoryName }

# Top-level files first
$rootFiles = $allFiles | Where-Object { $_.DirectoryName -eq $StageRoot }
if ($rootFiles) {
    $lines.Add('    SetOutPath "$INSTDIR"')
    foreach ($f in $rootFiles) {
        $lines.Add('    File "' + $f.FullName + '"')
    }
}

# Subdirectories (chrome/, bin/, extensions/...)
foreach ($g in $grouped | Sort-Object Name) {
    if ($g.Name -eq $StageRoot) { continue }
    $relDir = $g.Name.Substring($StageRoot.Length).TrimStart('\')
    $nsisDir = '$INSTDIR\' + $relDir
    $lines.Add('    SetOutPath "' + $nsisDir + '"')
    foreach ($f in $g.Group) {
        $lines.Add('    File "' + $f.FullName + '"')
    }
}

$lines.Add("!macroend")

[System.IO.File]::WriteAllLines($NshFile, $lines, [System.Text.Encoding]::ASCII)

$nshLines = (Get-Content $NshFile).Count
Write-Host ("    -> bb_files.nsh ({0} lines, {1} File entries)" -f $nshLines, $allFiles.Count) -ForegroundColor Green
